MAX_REFUND_YEARS = 11
REF_AGE_DELTA = 5


STATS = {"MMC" : {'Nbre Total': 0,'Nbre refArch': 0,'Nbre Dateferiee':0, 'Nbre nonsoumisro':0, 'Nbre finessfaux':0, 
                      'Nbre Adherent suspicieux':0 },
            "Mutest" : {'Nbre Total':0,'Nbre refArch': 0,'Nbre Dateferiee':0, 'Nbre nonsoumisro':0, 'Nbre finessfaux':0, 
                      'Nbre Adherent suspicieux':0 }
                         }

NONRO_PRESTA = ['1e Lentille NRSS SMIB',
'2e Lentille NRSS SMIB',
'ABANR',
'ACC',
'ACCADU',
'ACCAE',
'ACCCU',
'ACCCUR',
'ACCG',
'ACCM',
'ACTDNR',
'ACU',
'ACUPON',
'ADDIC',
'ADO',
'AIDADO',
'AIDNAI',
'ALESE',
'ALLER',
'AMNIOC',
'ANTGRVaccin non Remboursable par la Sécurité Sociale',
'APPNR',
'APS',
'AROMAC',
'AROMAT',
'ARTERA',
'AURIC',
'Acc.Enfant Cure NRSS',
'Accompagnement Ad/Enf SC',
'Accompagnement Ad/Enf SNC',
'Accompagnement Adulte SC',
'Accompagnement Adulte Secteur Conventionné',
'Accompagnement Adulte/Enfant Sect non Conventionné',
'Accompagnement Adulte/Enfant Secteur Conventionné',
'Accompagnement Enfant',
'Accompagnement Enfant Cure Thermale',
'Accompagnement Enfant Cure Thermale NRSS',
'Accompagnement Enfant M',
'Accompagnement Enfant SC',
'Accompagnement Enfant Secteur Conventionné',
'Accompagnement Enfant Secteur non Conventionné',
'Accompagnement Enft Cure',
'Accompagnement Enft SNC',
'Accompagnement Psy',
'Actes Dentaire NR',
'Actes biologie non remboursés Sécurité Sociale',
'Actes biologique NR',
'Actes biologiques NR',
'Acupuncture',
'Acupuncture et Homéopathie',
'Acupuncture\-Homéopathie',
'Aide sociale Adoption',
'Aide sociale naissance',
'Aliments sans Gluten',
'Allocation Adoption',
'Allocation frais de maternité',
'Allocation frais maternit',
'Alèse NRSS',
'Alèse non remboursée ss',
'Ambulances Agrées NR',
'Ambulances Agrées Non Remboursables',
'Amniocentèse non Remb SS',
'Amniocentèse non Remboursée par Sécurité Sociale',
'Antipaludéen prescrit NR',
'Appareillage non Remb SS',
'Appareillage non Remboursé par la Sécurité Sociale',
'Aromathérapie consult',
'Aromathérapie produits',
'Art\-thérapie',
'Auriculotthérapie',
'B NR',
'B NR',
'BILNUT',
'BIONEU',
'BONDEN',
'BONOEN',
'BONOGC',
'BONOPC',
'BONOPT',
'BONROP',
'BONUS DENTAIRE',
'BONUS OPTIQUE',
'BONUS OPTIQUE Enfant',
'BONUS OPTIQUE Faibl Corr',
'BONUS OPTIQUE Faible Corr',
'BONUS OPTIQUE Forte Corr',
'BONUS OPTIQUE Lunettes',
'BONUS OPTIQUE MUTUELLE',
'BONUS RENFORT OPTIQUE',
'BRIDGR',
'Bilan nutritionnel',
'Bioénergie et Neurostimul',
'Bioénergie et Neurostimulation élec transcutée',
'Bridges Refusés par la SS',
'CBD',
'CBD\-NR',
'CHIOPD',
'CHIOPG',
'CHIOPT',
'CHIROP',
'CHMATS',
'CIRCON',
'COADP',
'COASPO',
'COMPAL',
'CONFEM',
'CONPNR',
'CONTRA',
'COUCHE',
'COUDVI',
'COUNR',
'CURR',
'Chamb Matern SC Supplémt',
'Chamb Matern SNC Supplémt',
'Chamb.Particulière G SNC',
'Chamb.Particulière SNC',
'Chamb.avec hébergement',
'Chamb.avec hébergement SC',
'Chamb.avec hébgt SC \+8j',
'Chamb.avec hébgt SNC \+8j',
'Chamb.sans hébergement SC',
'Chamb.sans hébergement sc',
'Chamb.sans hébergt SNC',
'Chambre Maternité SC Supplément',
'Chambre Maternité SNC Supplément',
'Chambre Part. avec hébergement SC au délà 8 jours',
'Chambre Part. avec hébergement SNC au délà 8 jours',
'Chambre Particulière sans hébergement SNC',
'Chiropractie',
'Chirurgie Oeil droit',
'Chirurgie Oeil gauche',
"Chirurgie de l'Oeil",
'Coach en develop perso',
'Coach en développement personnel',
'Coach sportif',
'Compléments alimentaires',
'Contracep Patch Pil Stéri',
'CONPPS',
'Contraceptifs presc. NR',
'Contraceptifs prescrits non remboursables',
'Contraception',
'Contraception Féminine',
'Contraception Patch/Pilule/Stérilet',
'Couche NRSS',
'Couche non remboursée ss',
'Cour.Dent.NR dent vivante',
'Couronne Dentaire non remb. sur dent vivante',
'Couronne Dentaire non remboursable sauf provisoire',
'Couronne Dentaire nonremb',
'DCACOL',
'DCCU',
'DCD',
'DCS',
'DEBOFI',
'DEBOOR',
'DEBOPR',
'DETOX',
'DHEPAB',
'DIET',
'DINFUR',
'DPORHU',
'Dent Bonus fid. Ortho Acc',
'Dent Bonus fid. Ortho NC',
'Dent Bonus fid. Orthodontie Acc.',
'Dent Bonus fid. Orthodontie Acc. SNC',
'Dent Bonus fid. Proth Acc',
'Dent Bonus fid. Prothèses Acc',
'Dent Bonus fid. Prothèses Acc SNC',
'Dent Bonusfid Proth Ac NC',
'Dentaire Bonus de fidélité',
'Dentaire Bonus fidélité',
'Dep Cancer Col Uterus',
'Dep Cancer du Colon',
'Dep Hépatite B',
'Dep Infection urinaire',
'Dep Polyart rhumotoid',
'Dep Polyarthrite rhumotoid',
"Depistage du cancer du col de l'uterus",
'Diététiciens',
'Décès',
'Dépistage Cancer du Sein',
'Dépistage H1N1 ou VIH',
'Dépistage Hépatite B',
'Dépistage du Cancer du Sein',
'EEP',
'ENDO',
'ERGOTE',
'ETIOPA',
'Endodontie non remboursée',
'Endodontie non remboursée',
'Entretien Evaluation Psy',
'Ergothérapie',
'Etiopathie',
'FIVNR',
'FJ',
'FJ Sortie SNC',
'FJA',
'FRAFUN',
'FSNR',
'Forfait Journalier',
'Forfait Journalier Jour de Sortie',
'Forfait Journalier SNC',
'Forfait Journalier Secteur non conventionné',
'Forfait Journalier Sortie',
'Forfait Journalier Sortie Secteur non Conventionné',
'Forfait Mariage',
'Forfait Proth Fixes HN',
'Forfait Prothèses Fixes Hors Nomenclature',
'Forfait soins divers NR',
'Frais Funéraire',
'Frais Hosp Tv Tel Chir',
'Frais Hosp Tv Tel Mat',
'Frais Hosp Tv Tel Médi',
'Frais Hosp Tv Tel Repos',
'Frais Hospitalisation TV et Téléphone chirurgie',
'Frais Hospitalisation TV et Téléphone maternité',
'Frais Hospitalisation TV et Téléphone médicale',
'Frais Hospitalisation TV et Téléphone repos conv',
'Frais Journaux',
'Frais Téléphone',
'Frais de Téléphone sur justificatifs',
'Frais de Télévision',
'Frais de Télévision Chir',
'Frais de Télévision H SNC',
'Frais de Télévision Hosp.',
'Frais de Télévision Hospitalisation',
'Frais de Télévision Hospitalisation SNC',
'Frais de Télévision Med',
'Frais de Télévision en Chirurgie',
'Frais de Télévision en Medecine',
'Frais journaux Hospitalisation sous Justificatifs',
'Fécondation in Viro NR',
'Fécondation in Viro Non remboursée',
'GEMMOT',
'GLUPA',
'Gemmothérapie produits',
'H1NVIH',
'HOMEOC',
'HOMPNR',
'HUILES',
'HYPNOS',
'Homéopathie Prescirte non remboursée',
'Homéopathie consult NR',
'Homéopathie consultation NR',
'Homéopathie prescrite NR',
'Huiles Essentielles',
'Huiles et gélules CBD',
'Huiles et gélules CBD NR',
'Huiles et gélules CBD non remboursé',
'Huiles et produits DETOX',
'Hypnose',
'IMPLAN',
'IMPR',
'INLAYR',
'IVG NR',
'IVG Non remboursée',
'IVGNR',
'Implant',
'Implantologie non remb.',
'Implantologie non remboursée',
'Inlay Onlay non remboursé',
'Inlay et Onlay non remboursé',
'JOURNO',
'KISIO',
'Kiné Méthode Mézières NR',
'Kinésiologie',
'LASMY1',
'LASMY2',
'LASMYO',
'LEN1R',
'LEN2R',
'LENM1R',
'LENM2R',
'LENMR',
'LENMRE',
'LENMRG',
'LENMRP',
'LISPOR',
'LLENMR',
'LUNF1',
'LUNF1A',
'LUNF2',
'LUNF2A',
'LUNF3',
'LUNF3A',
'Licence sportive',
'MARIA',
'MARIAG',
'MEDDOU',
'MEDNOU',
'MEDNR',
'MEDPNR',
'MESOTH',
'MEZIER',
'MICROK',
'MUSIT',
'MYOENF',
'MYOGC',
'MYOPC',
'Micro Kiné',
'Monture Optique F1',
'Monture Optique F1A',
'Monture Optique F2',
'Monture Optique F2A',
'Monture Optique F3',
'Monture Optique F3A',
'Monture Optique Forfait1 Contrat Resp',
'Monture Optique Forfait1A Contrat Resp',
'Monture Optique Forfait2 Contrat Resp',
'Monture Optique Forfait2A Contrat Resp',
'Monture Optique Forfait3 Contrat Resp',
'Monture Optique Forfait3A Contrat Resp',
'Musicothérapie',
'Méd prescrits non Remb',
'Médecines Douces',
'Médecines Nouvelles',
'Médicaments non Remboursable',
'Médicaments non Remboursé',
'Médicaments prescrits non Remboursables',
'Mésothérapie',
'NAI',
'NATURO',
'NUTRI',
'Naturopathie',
'Nutritionniste',
'OBES',
'OBONLU',
'OLFAC',
'OLIGO',
'OPBOFI',
'OPTBON',
'OPTMR',
'ORTHN',
'ORTNR\+',
'OST',
'OSTDEN',
'OSTPO',
'Olfactothérapie',
'Oligothérapie',
'Optique Bonus de fidélité',
'Orthodontie Adulte NR\+',
'Orthodontie Adulte Non remboursée sécu',
'Orthodontie HN',
'Orthodontie hors nomenclature',
'Ostéodensitométrie',
'Ostéopathie',
'Ostéoporose',
'Ostéoporose analyses',
'PALU',
'PAMR',
'PAR',
'PARR',
'PATBLA',
'PATCON',
'PATDOU',
'PATMIN',
'PATTAB',
'PAUM',
'PB NR',
'PDTR',
'PEDI',
'PEDINR',
'PERIDU',
'PFCR',
'PFMR',
'PH NR',
'PHN',
'PHNR',
'PHPNR',
'PHYSIO',
'PHYTO',
'PHYTOC',
'PILCON',
'PILENT',
'PL MET',
'PODCNR',
'PODONR',
'PORTNR',
'PPORNR',
'PPRONR',
'PREPNR',
'PRESER',
'PROBIO',
'PROHN',
'PSYCHO',
'PSYCOV',
'PSYMOT',
'PSYTHE',
'PTPNR',
'Parodontologie Non Remb',
'Parodontologie Non Remboursée',
'Parodontologie refusée',
'Part Mut Verre D Optique Cor mixte AF Cont.Res',
'Part Mut Verre D Optique Cor mixte AF PNR',
'Part Mut Verre D Optique Cor mixte CF Cont.Res',
'Part Mut Verre D Optique Cor mixte CF PNR',
'Part Mut Verre D Optique Correction mixte Cont.Res',
'Part Mut Verre D Optique Correction mixte PNR',
'Part Mut Verre G Optique Cor mixte AF Cont.Res',
'Part Mut Verre G Optique Cor mixte AF PNR',
'Part Mut Verre G Optique Cor mixte CF Cont.Res',
'Part Mut Verre G Optique Cor mixte CF PNR',
'Part Mut Verre G Optique Correction mixte Cont.Res',
'Part Mut Verre G Optique Correction mixte PNR',
'Part Mut Verre Gauche Optique Unifocal',
'Part Mut Verre droit Optique Cor Mixte ACS',
'Part Mut Verre droit Optique Faibl.Cor ACS',
'Part Mut Verre droit Optique Faibl.Cor Contrat Res',
'Part Mut Verre droit Optique Forte Cor Contrat Res',
'Part Mut Verre droit Optique Forte Cor PNR',
'Part Mut Verre droit Optique Forte.Cor ACS',
'Part Mut Verre droit Optique Hyp.compl Contrat Res',
'Part Mut Verre droit Optique Hyp.compl PNR',
'Part Mut Verre droit Optique Multifocal/Progressif',
'Part Mut Verre droit Optique Unifocal',
'Part Mut Verre droit Progressif faible correction',
'Part Mut Verre droit Progressif forte correction',
'Part Mut Verre droite Optique Multifocal',
'Part Mut Verre gauch Optique FaibleCor Contrat Res',
'Part Mut Verre gauch Optique Forte Cor Contrat Res',
'Part Mut Verre gauch Optique Hyp compl Contrat Res',
'Part Mut Verre gauch Optique Multifocal/Progressif',
'Part Mut Verre gauche Optique Faibl.Cor ACS',
'Part Mut Verre gauche Optique Forte Cor PNR',
'Part Mut Verre gauche Optique Forte.Cor ACS',
'Part Mut Verre gauche Optique Hyp.compl PNR',
'Part Mut Verre gauche Optique Multifocal',
'Part Mut Verre gauche Progressif faible correction',
'Part Mut Verre gauche Progressif forte correction',
'Part Mutuelle 1er Verre Optique Multifocal C BLEU',
'Part Mutuelle 1er Verre Optique Unifocal C BLEU',
'Part Mutuelle 2me Verre Optique Multifocal C BLEU',
'Part Mutuelle 2me Verre Optique Unifocal C BLEU',
'Part Mutuelle Lentilles non RembSS Faible correct',
'Part Mutuelle Lentilles non RembSS Forte correct',
'Part Mutuelle Prothèse Orthopédique non remboursée',
'Part Mutuelle Verre droit Multif.Sphérocylindrique',
'Part Mutuelle Verre droit Multifocal Sphérique',
'Part Mutuelle Verre droit Optique FaibleCorrection',
'Part Mutuelle Verre droit Optique Forte Correction',
'Part Mutuelle Verre droit Optique Simple',
'Part Mutuelle Verre droit Unif. Faible Correction',
'Part Mutuelle Verre droit Unif. Forte Correction',
'Part Mutuelle Verre droit Unif. Sphérocylindrique',
'Part Mutuelle Verre droit Unifocal Sphérique',
'Part Mutuelle Verre droit faible correction',
'Part Mutuelle Verre droit forte correction',
'Part Mutuelle Verre gauche Multifocal Sphérique',
'Part Mutuelle Verre gauche Optique FaiblCorrection',
'Part Mutuelle Verre gauche Optique ForteCorrection',
'Part Mutuelle Verre gauche Optique Simple',
'Part Mutuelle Verre gauche Unif. Faible Correction',
'Part Mutuelle Verre gauche Unif. Forte Correction',
'Part Mutuelle Verre gauche Unif. Sphérocylindrique',
'Part Mutuelle Verre gauche Unifocal Sphérique',
'Part Mutuelle Verre gauche faible correction',
'Part Mutuelle Verre gauche forte correction',
'Part Mutuelle Verre gaucheMultif.Sphérocylindrique',
'Part Mutuelle Verres Optiques Faible Correction',
'Part Mutuelle Verres Optiques Forte Correction',
'Part./Achat Prot.Auditive',
'Part./Transport non Remb.',
'Part.Mut / Lunettes NRSS',
'Part.Mut 1 Verre MF CBleu',
'Part.Mut 1 Verre UF CBleu',
'Part.Mut 1er Verre multif',
'Part.Mut 1er Verre unifoc',
'Part.Mut 2 Verre MF CBleu',
'Part.Mut 2 Verre UF CBleu',
'Part.Mut 2e Verre multfoc',
'Part.Mut 2e Verre unifoc',
'Part.Mut./Lentilles NRSS',
'Part.Mut.1e Lentille NRSS',
'Part.Mut.2e Lentille NRSS',
'Part.Mut.Cure Refusée SS',
'Part.Mut/1er Verre Prog',
'Part.Mut/2ème Verre Prog',
'Part.Mut/Lent NRSS FaibCo',
'Part.Mut/Lent NRSS FortCo',
'Part.Mut/Lentill NRSS Enf',
'Part.Mut/Lentilles NRSS L',
'Part.Mut/Orthodontie NR',
'Part.Mut/Prothèses DentNR',
'Part.Mut/Prothèses Dentaires non remboursées',
'Part.Mut/Verres Faibl Cor',
'Part.Mut/Verres Forte Cor',
'Part.Mutuelle/Lentilles non Remb.SS Luxembourg',
'Part/Pile Entr P.Auditive',
'Part/Prot.Orthopédique NR',
'PartMut Ver D Co mixte CR',
'PartMut Ver D Faib.Cor CR',
'PartMut Ver D Fort.Cor CR',
'PartMut Ver D Hyp comp CR',
'PartMut Ver D mixte AF CR',
'PartMut Ver D mixte CF CR',
'PartMut Ver G Co mixte CR',
'PartMut Ver G Faib.Cor CR',
'PartMut Ver G Fort.Cor CR',
'PartMut Ver G Hyp.comp CR',
'PartMut Ver G mixte AF CR',
'PartMut Ver G mixte CF CR',
'PartMut VerD Co mixte PNR',
'PartMut VerD Cor Mixt ACS',
'PartMut VerD Faib.Cor ACS',
'PartMut VerD Faib.Cor PNR',
'PartMut VerD Fort Cor ACS',
'PartMut VerD Fort.Cor PNR',
'PartMut VerD Hyp comp PNR',
'PartMut VerD mixte AF PNR',
'PartMut VerD mixte CF PNR',
'PartMut VerG Co mixte PNR',
'PartMut VerG Faib.Cor ACS',
'PartMut VerG Faib.Cor PNR',
'PartMut VerG Fort Cor ACS',
'PartMut VerG Fort.Cor PNR',
'PartMut VerG Hyp comp PNR',
'PartMut VerG mixte AF PNR',
'PartMut VerG mixte CF PNR',
'PartMut Verre D Faibl.Cor',
'PartMut Verre D Forte Cor',
'PartMut Verre D MulF/Prog',
'PartMut Verre D Multifoc.',
'PartMut Verre D Prog GC',
'PartMut Verre D Prog PC',
'PartMut Verre D Simple',
'PartMut Verre D Simple GC',
'PartMut Verre D Simple PC',
'PartMut Verre D Unifocal',
'PartMut Verre G Faibl.Cor',
'PartMut Verre G Forte Cor',
'PartMut Verre G MulF/Prog',
'PartMut Verre G Multifoc.',
'PartMut Verre G Prog GC',
'PartMut Verre G Prog PC',
'PartMut Verre G Simple',
'PartMut Verre G Simple GC',
'PartMut Verre G Simple PC','PartMut Verre G Unifocal','PartMut Verre droit Optique Faibl.Cor PNR','PartMut Verre gauche Optique Faibl.Cor PNR','PartMut VerreD M\-Sphé.Cyl','PartMut VerreD M\-Sphériqu','PartMut VerreD U\-Sphé.Cyl','PartMut VerreD U\-Sphériqu','PartMut VerreD Uni\-FaibCo',
'PartMut VerreD Uni\-FortCo',
'PartMut VerreG M\-Sphé.Cyl',
'PartMut VerreG M\-Sphériqu',
'PartMut VerreG U\-Sphé.Cyl',
'PartMut VerreG U\-Sphériqu',
'PartMut VerreG Uni\-FaibCo',
'PartMut VerreG Uni\-FortCo',
'Participation Mut Pile entreti Prothè\xadse Auditive',
'Participation Mutuelle / 1er Verre Opt progressif',
'Participation Mutuelle / 2ème Verre Opt progressif',
'Participation Mutuelle / Transport non remboursé',
'Participation Mutuelle 1er Verre Optique Multfocal',
'Participation Mutuelle 1er Verre Optique Unifocal',
'Participation Mutuelle 2me Verre Optique Multfocal',
'Participation Mutuelle 2ème Verre Optique Unifocal',
'Participation Mutuelle Achat Prothè\xadse Auditive',
'Participation Mutuelle Cure Refusée SS',
'Participation Mutuelle Lentilles non RembSS Enfant',
'Participation Mutuelle sur 1\xadre Lentille NRSS',
'Participation Mutuelle sur 1ère Lentille NRSS SMIB',
'Participation Mutuelle sur 2\xadme Lentille NRSS',
'Participation Mutuelle sur 2ème Lentille NRSS SMIB',
'Participation Mutuelle sur Lentilles non Remb.SS',
'Participation Mutuelle sur Lunettes non Remb SS',
'Participation Mutuelle sur Orthodontie NR',
'Patch Anti Tabac',
'Patch Antidouleur',
'Patch Contraceptif',
'Patch Dent BlanchissantNR',
'Patch Dentaire Blanchissant non remboursé',
'Patch Minceur',
'Pharm non Remboursable',
'Pharm prescrite non Remb',
'Pharm.non Remboursable',
'Pharma. non Remboursable',
'Pharmacie non Remboursable',
'Pharmacie prescrite non Remboursable',
'Physiothérapie',
'Phytothérapie',
'Phytothérapie',
'Phytothérapie consult NR',
'Phytothérapie consultation NR',
'Pilules Contraceptives',
'Plaque Métal NR SS',
'Plaque Métal Non remboursée par Sécurité Sociale',
'Podologie NRSS',
'Podologie NRSS complément',
'Podologie non remboursée ss',
'Podologie non remboursée ss complément',
'Posthectomie NR',
'Posthectomie non remboursée',
'Prime de Mariage',
'Probiotiques',
'Prot dentaire hors nomenclature',
'Prot hors nomenclature',
'Prot. amov déf. résine NR',
'Prot. amov. déf. métal NR',
'Proth. dent provisoire NR',
'Proth. fixe Métalique NR',
'Proth. fixe céramique NR',
'Prothèse Dentaire HN',
'Prothèse Dentaire par Chirurgien Dentiste HN',
'Prothèse amovible définitive résine non remb.',
'Prothèse amovible définitive métalique non remb.',
'Prothèse dentaire provisoire non remboursée',
'Prothèse fixe Métallique non remboursée',
'Prothèse fixe céramique non remboursée',
'Prél Sanguin NR',
'Prélèvement Sanguin NR',
'Prélèvement Sanguin non Remboursé par SS',
'Préparations magistra. NR',
'Préservatifs',
'Psychologie',
"Psychologue entreteien d'évaluation",
'Psychomotricité',
'Psychothérapie',
'Pédicure',
'Pédicure (Médecine Douce Plus)',
'Pédicure NRSS',
'Pédicure non remboursée ss',
'Péridurale non Remb SS',
'Péridurale non Remboursée par la Sécurité Sociale',
'R COR',
'RADINR',
'RADPNR',
'REFLEX',
'REFPLA',
'RPNR',
'RSCDNR',
'Radio Scan Dentaire NR',
'Radiologie NR',
'Radiologie prescrite NR',
'Rapatriement de Corps',
'Réflexologie',
'Réflexologie plantaire',
'Réparation prot. dent. NR',
'Réparation sur prothèse dentaire non remboursée',
'SC HN',
'SEXOLO',
'SHIAT',
'SHO',
'SHO\+8J',
'SHOG',
'SHOSH',
'SHOSHG',
'SOPHRO',
'SPRFFH',
'SPRHN',
'Sexologie',
'Shiatsu',
'Soins Conserv/Dentiste HN',
'Soins Conservateurs par Chirurgien Dentiste HN',
'Sophrologie',
'Substitut nicotinique',
'Supplément Chambre Particulière avec hébergement',
'Supplément de Chambre Particulière G SNC',
'Supplément de Chambre Particulière SNC',
'Supplémnt Chambre Particulière avec hébergement SC',
'Supplémnt Chambre Particulière sans hébergemen sc',
'Supplémnt Chambre Particulière sans hébergement SC',
'Séance Psychologue COVID',
'TABAC',
'TABACP',
'TB NR',
'TDSR',
'TEL',
'TEST',
'TESTGR',
'THECOU',
'TNS',
'TRANR',
'TVCH',
'TVHOSP',
'TVME',
'TVTEL1',
'TVTEL2',
'TVTEL6',
'TVTEL7',
'Test Grossesse',
'Test de Grossesse',
'Thérapie de couple',
'Trait Laser Myopie Enfant',
'Trait Laser Myopie FaibCo',
'Trait Laser Myopie FortCo',
'Trait Laser Myopie Oeil 1',
'Trait Laser Myopie Oeil 2',
'Traitement Anti Tabagique',
'Traitement Anti Tabagique prescit',
'Traitement AntiTabac Pr.',
'Traitement Laser Myopie',
'Traitement Laser Myopie Enfant',
'Traitement Laser Myopie Faible Correction',
'Traitement Laser Myopie Forte Correction',
'Traitement Laser Myopie Oeil Droit',
'Traitement Laser Myopie Oeil Gauche',
"Traitement de l'Obésité",
'Traitement des Addictions',
'Traitement des Allergies',
'Transport non remboursé',
'Transport prescrit non remboursé hors cure & hosp.',
'V1MFCB','V1UFCB','V2MFCB','V2UFCB','VAC',
'VACCINS REFUSES PAR SS',
'VACNPR','VACPNR','VACR',
'VDCRA',
'VDCRAC',
'VDCRAF',
'VDCRC',
'VDCRCF',
'VDCRF',
'VDCSA',
'VDCSAC',
'VDCSC',
'VDNRA',
'VDNRAC',
'VDNRAF',
'VDNRC',
'VDNRCF',
'VDNRF',
'VER1MF',
'VER1UF',
'VER2MF',
'VER2UF',
'VERDGC',
'VERDMC',
'VERDMP',
'VERDMS',
'VERDMU',
'VERDPC',
'VERDPG',
'VERDPP',
'VERDS',
'VERDSG',
'VERDSP',
'VERDU',
'VERDUC',
'VERDUG',
'VERDUP',
'VERDUS',
'VERF1',
'VERF1A',
'VERF2',
'VERF2A',
'VERF3',
'VERF3A',
'VERGGC',
'VERGMC',
'VERGMP',
'VERGMS',
'VERGMU',
'VERGPC',
'VERGPG',
'VERGPP',
'VERGS',
'VERGSG',
'VERGSP',
'VERGU',
'VERGUC',
'VERGUG',
'VERGUP',
'VERGUS',
'VERMGC',
'VERMPC',
'VERP1',
'VERP2',
'VGCRA',
'VGCRAC',
'VGCRAF',
'VGCRC',
'VGCRCF',
'VGCRF',
'VGCSA',
'VGCSC',
'VGNRA',
'VGNRAC',
'VGNRAF',
'VGNRC',
'VGNRCF',
'VGNRF',
'Vaccin Antigrippe',
'Vaccin NR par SS',
'Vaccin prescrit non NR',
'Vaccin prescrit non remboursable SS',
'Vaccin prescrit ou non NR',
'Vaccin prescrit ou non et non remboursable SS',
'Verres Optiques F1',
'Verres Optiques F1A',
'Verres Optiques F2',
'Verres Optiques F2A',
'Verres Optiques F3',
'Verres Optiques F3A',
'Verres Optiques Forfait1 Cont. Resp',
'Verres Optiques Forfait1A Cont. Resp',
'Verres Optiques Forfait2 Cont. Resp',
'Verres Optiques Forfait2A Cont. Resp',
'Verres Optiques Forfait3 Cont. Resp',
'Verres Optiques Forfait3A Cont. Resp',
'séance accompagnement psychologue']


 





